### ISSUE TITLE
Don't use the term "Issue" to describe each newsletter release

### ISSUE THREAD

**Issue by felicianotech** [davidsneighbour/hugonewsletter.com#5]
Feedback via email:

> The Newsletter was Awesome but please change the subject, it is confusing for git users, for a while I thought that someone created a new issue.
>
> Don't create issues, create Newsletters!

**Comment by davidsneighbour** [comment]
Not sure how this topic came up, but "issue" is basically the correct English term for a regular publication. So we won't get rid of it. 

What I would understand is that the subject of the email should not contain "issue". That makes sense. I think we should in any way have readable subjects like "New graphic features, 5 new themes and more" instead of "Hugo newsletter October issue". Future newsletters will be sent out this way ;)

**Comment by felicianotech** [comment]
Sounds like a good idea.
